name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Folder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The files to upload
          branch: gh-pages # The destination branch
          target-folder: previews/pr-${{ github.event.number }} # The subfolder
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Preview Link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 **PR Preview Ready!**
            You can view the changes here: [https://tidyswan.com/decader/previews/pr-${{ github.event.number }}/](https://tidyswan.com/decader/previews/pr-${{ github.event.number }}/)
